--TEST--
Bug #73254 (Incorrect indentation generated by fastjson_encode() with JSON_PRETTY_PRINT)
--EXTENSIONS--
fastjson
--FILE--
<?php

echo fastjson_encode([fastjson_encode([1], JSON_PRETTY_PRINT)]), "\n";

$fp = fopen('php://temp', 'r');
$data = ['a' => $fp];
echo fastjson_encode($data), "\n";
echo fastjson_encode([fastjson_encode([1], JSON_PRETTY_PRINT)]), "\n";

?>
--EXPECT--
["[\n    1\n]"]

["[\n    1\n]"]
